const API_BASE = '';
const pngPage = (file, page) => `png-mockups/${file.replace(/\.(pdf|png)$/i, '').replace(/[^A-Za-z0-9_-]+/g, '-').replace(/^-|-$/g, '')}/page-${String(page).padStart(3, '0')}.png`;
const projects = [
  {name:'ManavSeva', type:'Donor–NGO mobile platform', year:'2025', accent:'#6fbd75', swatches:['#1f5c3c','#72b85d','#f4ede0'], role:'Product design · UX strategy', problem:'Donors and NGOs were speaking past one another. ManavSeva needed one calm place where giving could become visible, trackable impact.', process:'Mapped four distinct user roles, simplified the donation journey, and built a modular mobile system around trust and clarity.', outcome:'A shared language for donors, NGOs, volunteers, and beneficiaries.', visual:'green'},
  {name:'CA Mitra', type:'Startup ↔ chartered accountant fintech', year:'2025', accent:'#51c7c4', swatches:['#0f7774','#a7d9d0','#e7f1ea'], role:'UI direction · Brand system', problem:'A complex service had to feel approachable to early-stage founders without losing financial confidence.', process:'Explored twin directions: the tactile authority of a ledger stamp and a modern teal system set in Space Grotesk.', outcome:'A confident fintech launchpad with a clearer first step for founders.', visual:'teal', mockupLayout:'desktop', mockups:[['CA mitra web.pdf','CA Mitra website mockup']], frames:[['01 / OPENING','The first website page establishes the CA Mitra proposition and gives the visitor an immediate orientation.'],['02 / VALUE','The second page clarifies the product value and translates financial support into a founder-friendly promise.'],['03 / TRUST','The third page builds confidence through credibility cues and a calmer information hierarchy.'],['04 / SERVICES','The fourth page organises the CA and startup services into a clear, scannable path.'],['05 / PROCESS','The fifth page shows how a founder moves from a need to the right accounting partner.'],['06 / NEXT STEP','The final page closes the journey with a focused enquiry or connection action.']]},
  {name:'DermaScope', type:'AI skin & hair analysis website', year:'2024', accent:'#e28fa9', swatches:['#7a2340','#d98fa3','#f5dfe5'], role:'Web design · Information architecture', problem:'An AI health scan can make people anxious. The interface needed to turn an intimidating result into a calm next step.', process:'Organised multi-page education around questions users actually ask, balancing maroon authority with a softer pink visual voice.', outcome:'Clinical clarity with a human edge.', visual:'pink'},
  {name:'KASA Traders', type:'Business card + interactive catalogue', year:'2024', accent:'#c9aa68', swatches:['#173b32','#b8934d','#f4efe3'], role:'Identity · Catalogue design', problem:'A home textiles business needed a digital storefront that could carry the tactility of its products across distance.', process:'Created a warm forest-green and muted-gold system with a catalogue rhythm inspired by editorial product books.', outcome:'A more considered bridge from UAE sourcing to Indian homes.', visual:'gold', mockupStyle:'catalogue', flipbookFiles:['KASA pamphlet.pdf','KASA Traders Catalogue.pdf'], mockups:[['KASA pamphlet.pdf','KASA pamphlet'],['KASA Traders Catalogue.pdf','KASA Traders catalogue'],['print KASA (1).pdf','KASA print collateral']], pageSets:[['KASA pamphlet.pdf',2],['KASA Traders Catalogue.pdf',47],['print KASA (1).pdf',2]]},
  {name:'UPES MUN', type:'Campaign identity · event design system', year:'2024', accent:'#b68be0', swatches:['#18283a','#c9a45c','#e9e1d2'], role:'Design lead · Print · Social · Signage', problem:'A large student conference needed one visual language that could move confidently between screens, rooms, and delegate hands.', process:'Built a complete event system across social posts, brochures, placards, standees, prize posters, and registration collateral.', outcome:'A recognisable, coherent campaign identity for every stage of the delegate experience.', visual:'purple', mockupStyle:'campaign', flipbookPdf:'Brochure.pdf', flipbookPages:14, mockups:[['Brochure.pdf','Brochure'],['Chitpad.pdf','Chitpad'],['Committee Standees.pdf','Committee standees'],['Folder (1).pdf','Delegate folder'],['Insta Post.pdf','Instagram post'],['main standees.pdf','Main standees'],['Placards.pdf','Placards'],['Prize posters.pdf','Prize posters'],['Register Post.pdf','Registration post'],['story.pdf','Story format']], pageSets:[['Brochure.pdf',14],['Chitpad.pdf',1],['Committee Standees.pdf',6],['Folder (1).pdf',2],['Insta Post.pdf',2],['main standees.pdf',3],['Placards.pdf',1],['Prize posters.pdf',4],['Register Post.pdf',3],['story.pdf',14]]}
];
const grid = document.querySelector('#project-grid');
const dialog = document.querySelector('#project-dialog');
const dialogContent = document.querySelector('#dialog-content');
projects.forEach((project, index) => { const card = document.createElement('article'); const isManavSeva = project.name === 'ManavSeva'; const isDermaScope = project.name === 'DermaScope'; card.className=`project-card reveal${isManavSeva ? ' manav-card' : ''}`; card.style.setProperty('--accent', project.accent); card.dataset.testid=`project-card-${index}`; card.innerHTML=`<span class="project-index">0${index+1} / ${project.year}</span><div class="swatches">${project.swatches.map(color=>`<i style="background:${color}"></i>`).join('')}</div><h3>${project.name}</h3><p class="project-type">${project.type}</p><p>${project.role}</p><span class="project-expand">${isManavSeva || isDermaScope ? `View ${project.name} case study ↗` : '↗'}</span>`; card.addEventListener('click',()=>{if(isManavSeva){window.open('manav-seva.html','_blank');return}if(isDermaScope){window.open('dermascope.html','_blank');return}openProject(project)}); grid.append(card); });
function openProject(project){
  dialog.classList.add('case-dialog');
  const websiteMockup = project.mockupLayout === 'desktop' ? `<div class="dialog-website-mockup"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">WEBSITE MOCKUP · SIX FRAMES</p><p>Scroll through the full website, page by page.</p></div><div class="website-frame-list">${Array.from({length:6},(_,pageIndex)=>`<article class="website-frame-row ${pageIndex % 2 ? 'reverse' : ''}"><div class="frame-visual"><div class="desktop-shell"><div class="desktop-bar"><span></span><span></span><span></span><small>ca-mitra / website · frame ${String(pageIndex+1).padStart(2,'0')}</small></div><iframe src="mockups/CA%20mitra%20web.pdf#page=${pageIndex+1}&view=FitH" title="CA Mitra website frame ${pageIndex+1}"></iframe></div></div><div class="frame-explanation"><p class="frame-number">FRAME ${String(pageIndex+1).padStart(2,'0')}</p><h3>${project.frames[pageIndex][0].replace(/^\d+\s\/\s/,'')}</h3><span class="frame-arrow">${pageIndex % 2 ? '←' : '→'}</span><p>${project.frames[pageIndex][1]}</p></div></article>`).join('')}</div><p class="mockup-caption">Every PDF page is presented as its own desktop screen, with the design intent explained beside it.</p></div>` : '';
    const pageMockup = project.pageSets?.length ? `<section class="dialog-page-mockups ${project.mockupStyle}"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">${project.name.toUpperCase()} · PAGE-BY-PAGE MOCKUPS</p><p>Every source page is presented as its own desktop screen.</p></div><div class="page-frame-list">${project.pageSets.filter(([file])=>file !== project.flipbookPdf).flatMap(([file,pageCount])=>Array.from({length:pageCount},(_,pageIndex)=>({file,pageIndex}))).map(({file,pageIndex},frameIndex)=>{const pdfUrl=`mockups/${encodeURIComponent(file.replace(/\.pdf$/i, '.png'))}#page=${pageIndex+1}&view=FitH`;const frameName=project.mockupStyle === 'catalogue' ? `Catalogue spread ${frameIndex+1}` : `Campaign frame ${frameIndex+1}`;const arrow=frameIndex%2?'←':'→';return `<article class="page-frame-row ${frameIndex%2?'reverse':''}"><div class="page-frame-visual"><div class="desktop-shell"><div class="desktop-bar"><span></span><span></span><span></span><small>${project.name.toLowerCase()} · ${String(frameIndex+1).padStart(2,'0')}</small></div><iframe loading="lazy" src="${pdfUrl}" title="${project.name} page ${frameIndex+1}"></iframe></div></div><div class="page-frame-copy"><p class="frame-number">${String(frameIndex+1).padStart(2,'0')}</p><h3>${frameName}</h3><span class="frame-arrow">${arrow}</span><p>${project.mockupStyle === 'catalogue' ? 'A tactile product-led page with space for material, texture, and a slower catalogue rhythm.' : 'A campaign touchpoint carrying the event identity across print, social, signage, and delegate experience.'}</p></div></article>`}).join('')}</div></section>` : '';
  const catalogueMockup = project.mockupStyle === 'catalogue' ? `<section class="catalogue-flipbooks">${project.pageSets.filter(([file])=>project.flipbookFiles.includes(file)).map(([file,pageCount],bookIndex)=>`<section class="catalogue-flipbook" data-file="${file}" data-pages="${pageCount}" data-testid="kasa-flipbook-${bookIndex}"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">KASA ${file.includes('pamphlet') ? 'PAMPHLET' : 'CATALOGUE'} · FLIPBOOK</p><p>Use the arrows to turn through all ${pageCount} pages.</p></div><div class="flipbook-stage"><div class="desktop-shell flipbook-shell"><div class="desktop-bar"><span></span><span></span><span></span><small>kasa traders / ${file.includes('pamphlet') ? 'pamphlet' : 'catalogue'}</small></div><iframe class="flipbook-page" title="KASA ${file} page 1"></iframe></div><button class="flip-button flip-prev" type="button" aria-label="Previous page">←</button><button class="flip-button flip-next" type="button" aria-label="Next page">→</button></div><div class="flipbook-meta"><span class="flip-page-label">Page 01 / ${pageCount}</span><span class="flip-page-title">${file.replace('.pdf','')}</span></div><p class="flipbook-explanation">${file.includes('pamphlet') ? 'Brand introduction, material language, and the first impression of the KASA Traders identity.' : 'Product-led catalogue pages that let the viewer browse the range with an editorial, tactile rhythm.'}</p></section>`).join('')}<a class="mockup-jump" href="#other-mockups">See other mockups ↓</a></section>` : '';
  const campaignFlipbook = project.flipbookPdf ? `<section class="campaign-flipbook"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">UPES MUN BROCHURE · FLIPBOOK</p><p>Turn through all ${project.flipbookPages} brochure pages.</p></div><div class="flipbook-stage"><div class="desktop-shell flipbook-shell campaign-shell"><div class="desktop-bar"><span></span><span></span><span></span><small>upes mun / brochure</small></div><iframe class="campaign-flipbook-page" title="UPES MUN brochure page 1"></iframe></div><button class="flip-button campaign-prev" type="button" aria-label="Previous brochure page">←</button><button class="flip-button campaign-next" type="button" aria-label="Next brochure page">→</button></div><div class="flipbook-meta campaign-meta"><span class="campaign-page-label">Page 01 / ${project.flipbookPages}</span><span class="campaign-page-title">UPES MUN Brochure</span></div><p class="campaign-explanation">This brochure frame introduces the event narrative and carries the UPES MUN identity into a delegate-facing format.</p><a class="mockup-jump" href="#other-mockups">See other mockups ↓</a></section>` : '';
  const staticMockups = project.mockups?.filter(([file])=>!(project.flipbookFiles || []).includes(file) && file !== project.flipbookPdf) || [];
  const assetMockups = staticMockups.length ? `<section class="asset-mockups" id="other-mockups"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">OTHER COLLATERAL · DISTINCT MOCKUPS</p><p>Each remaining asset has its own presentation style.</p></div><div class="asset-mockup-grid">${staticMockups.map(([file,label],assetIndex)=>{const lower=label.toLowerCase();const variant=lower.includes('standee')?'standee':lower.includes('poster')?'poster':lower.includes('post')||lower.includes('story')?'social':lower.includes('placard')?'placard':lower.includes('folder')?'folder':lower.includes('chitpad')?'paper':'print';const explanation=variant==='standee'?'A tall event sign designed to carry the identity across a physical venue.':variant==='poster'?'A high-impact poster composition built for quick recognition at a distance.':variant==='social'?'A compact social frame adapted for fast reading and campaign consistency.':variant==='placard'?'A delegate-facing sign that keeps the event system legible in the room.':variant==='folder'?'A printed information container that brings the campaign into the delegate journey.':variant==='paper'?'A tactile print piece that shows the identity at hand-held scale.':'A print application that extends the visual system beyond the screen.';const pdfUrl=`mockups/${encodeURIComponent(file)}${file.includes('print KASA')?'#page=1&view=Fit':''}`;return `<figure class="asset-mockup ${variant}" data-testid="asset-mockup-${assetIndex}"><div class="asset-frame"><object data="${pdfUrl}" type="application/pdf" aria-label="${label} mockup"></object></div><figcaption><span>${label}</span><a class="mockup-open" href="${pdfUrl}" target="_blank" rel="noopener noreferrer">Open PDF ↗</a></figcaption><p class="asset-explanation">${explanation}</p></figure>`}).join('')}</div></section>` : '';
  const imageAssetMockups = staticMockups.length ? `<section class="dialog-page-mockups asset-page-mockups" id="other-mockups"><div class="website-mockup-heading"><p class="eyebrow" style="color:${project.accent}">OTHER COLLATERAL · FULL MOCKUPS</p><p>Each piece is shown at full size with its design role beside it.</p></div><div class="website-frame-list">${staticMockups.map(([file,label],assetIndex)=>{const lower=label.toLowerCase();const explanation=lower.includes('standee')?'A tall venue sign that carries the event identity across physical space.':lower.includes('poster')?'A high-impact poster designed for fast recognition from a distance.':lower.includes('post')||lower.includes('story')?'A social format that keeps the campaign consistent in a fast-scrolling feed.':lower.includes('placard')?'A delegate-facing sign that keeps the event system legible in the room.':lower.includes('folder')?'A printed information container that supports the delegate journey.':lower.includes('chitpad')?'A tactile hand-held piece that brings the identity into the room.':'A print application that extends the visual system beyond the screen.';return `<article class="website-frame-row asset-page-row ${assetIndex%2?'reverse':''}" data-testid="asset-page-${assetIndex}"><div class="frame-visual"><div class="desktop-shell"><div class="desktop-bar"><span></span><span></span><span></span><small>${project.name.toLowerCase()} / ${label.toLowerCase()}</small></div><img class="mockup-image" src="${pngPage(file,1)}" alt="${label} full mockup"></div></div><div class="frame-explanation"><p class="frame-number">${String(assetIndex+1).padStart(2,'0')} / ${staticMockups.length}</p><h3>${label}</h3><span class="frame-arrow">${assetIndex%2?'←':'→'}</span><p>${explanation}</p><a class="mockup-open" href="${pngPage(file,1)}" target="_blank" rel="noopener noreferrer">Open full image ↗</a></div></article>`}).join('')}</div></section>` : '';
  const mockups = project.mockupLayout === 'desktop' ? websiteMockup : project.mockupStyle === 'catalogue' ? `${catalogueMockup}${imageAssetMockups}` : project.mockupStyle === 'campaign' ? `${campaignFlipbook}${imageAssetMockups}` : project.mockups?.length ? imageAssetMockups : '';
  dialogContent.innerHTML=`<div class="dialog-body" style="--accent:${project.accent}"><p class="eyebrow" style="color:${project.accent}">${project.type} · ${project.year}</p><h2>${project.name}</h2><p>${project.role}</p><div class="case-grid"><div><b>THE PROBLEM</b><p>${project.problem}</p></div><div><b>THE PROCESS</b><p>${project.process}</p></div><div><b>THE OUTCOME</b><p>${project.outcome}</p></div></div>${mockups}</div>`;
  dialogContent.querySelectorAll('iframe[src*="mockups/"]').forEach(frame=>{const url=new URL(frame.src,location.href);const file=decodeURIComponent(url.pathname.split('/').pop()).replace(/\.png$/i,'.pdf');const page=Number(new URLSearchParams(url.hash.slice(1)).get('page'))||1;frame.replaceWith(Object.assign(document.createElement('img'),{src:pngPage(file,page),alt:frame.title,className:'mockup-image'}));});
  dialogContent.querySelectorAll('object[data*="mockups/"]').forEach(object=>{const file=decodeURIComponent(object.data.split('/').pop().split('#')[0]);const image=Object.assign(document.createElement('img'),{src:pngPage(file,1),alt:object.getAttribute('aria-label')||'Mockup preview',className:'mockup-image'});object.replaceWith(image);});
  dialogContent.querySelectorAll('.flipbook-page,.campaign-flipbook-page').forEach(frame=>{const image=document.createElement('img');image.className=`${frame.className} mockup-image`;image.alt=frame.title;frame.replaceWith(image)});
  if(project.mockupStyle === 'catalogue'){
    dialogContent.querySelectorAll('.catalogue-flipbook').forEach(flipbook=>{
      const file=flipbook.dataset.file; const pageCount=Number(flipbook.dataset.pages); const frame=flipbook.querySelector('.flipbook-page'); const pageLabel=flipbook.querySelector('.flip-page-label'); const pageTitle=flipbook.querySelector('.flip-page-title'); const explanation=flipbook.querySelector('.flipbook-explanation'); let currentPage=0;
      const renderPage=()=>{frame.src=pngPage(file,currentPage+1);frame.title=`KASA ${file} page ${currentPage+1}`;pageLabel.textContent=`Page ${String(currentPage+1).padStart(2,'0')} / ${pageCount}`;pageTitle.textContent=file.replace('.pdf','')+` · page ${currentPage+1}`;explanation.textContent=`${file.includes('pamphlet')?'Pamphlet':'Catalogue'} page ${currentPage+1}: a considered composition that builds KASA Traders’ tactile, warm product story.`;frame.classList.remove('page-turn');void frame.offsetWidth;frame.classList.add('page-turn');};
      flipbook.querySelector('.flip-prev').addEventListener('click',()=>{currentPage=(currentPage-1+pageCount)%pageCount;renderPage()}); flipbook.querySelector('.flip-next').addEventListener('click',()=>{currentPage=(currentPage+1)%pageCount;renderPage()}); renderPage();
    });
  }
  if(project.flipbookPdf){
    const flipbook=dialogContent.querySelector('.campaign-flipbook');
    const frame=flipbook.querySelector('.campaign-flipbook-page');
    const pageLabel=flipbook.querySelector('.campaign-page-label');
    const pageTitle=flipbook.querySelector('.campaign-page-title');
    const explanation=flipbook.querySelector('.campaign-explanation');
    let currentPage=0;
    const renderPage=()=>{frame.src=pngPage(project.flipbookPdf,currentPage+1);frame.title=`UPES MUN brochure page ${currentPage+1}`;pageLabel.textContent=`Page ${String(currentPage+1).padStart(2,'0')} / ${project.flipbookPages}`;pageTitle.textContent=`Brochure page ${currentPage+1}`;explanation.textContent=`Brochure page ${currentPage+1}: a campaign frame carrying the UPES MUN identity through the delegate journey.`;frame.classList.remove('page-turn');void frame.offsetWidth;frame.classList.add('page-turn')};
    flipbook.querySelector('.campaign-prev').addEventListener('click',()=>{currentPage=(currentPage-1+project.flipbookPages)%project.flipbookPages;renderPage()});
    flipbook.querySelector('.campaign-next').addEventListener('click',()=>{currentPage=(currentPage+1)%project.flipbookPages;renderPage()});
    renderPage();
  }
  history.pushState({project:project.name},'',`?project=${encodeURIComponent(project.name.toLowerCase().replace(/\s+/g,'-'))}`);
  dialog.showModal();
}
dialog.querySelector('.dialog-close').addEventListener('click',()=>{dialog.close();history.pushState({},'',location.pathname)}); dialog.addEventListener('click',event=>{if(event.target===dialog){dialog.close();history.pushState({},'',location.pathname)}}); addEventListener('popstate',()=>{if(dialog.open)dialog.close()});
const observer = new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.14}); document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
const progress = document.querySelector('#timeline-progress'); const timeline = document.querySelector('.timeline'); function updateTimeline(){const box=timeline.getBoundingClientRect(); const amount=Math.min(1,Math.max(0,(window.innerHeight*.7-box.top)/(box.height*.78))); progress.style.height=`${amount*100}%`;} window.addEventListener('scroll',updateTimeline,{passive:true}); updateTimeline();
const canvas=document.querySelector('#starfield'); const context=canvas.getContext('2d'); let stars=[]; const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches; function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); const count=reduced?45:innerWidth<700?75:150;stars=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.4+.2,a:Math.random()*.65+.15,s:Math.random()*.08+.01}));} function draw(){context.clearRect(0,0,innerWidth,innerHeight);stars.forEach(star=>{star.y-=star.s;if(star.y<0)star.y=innerHeight;context.beginPath();context.arc(star.x,star.y,star.r,0,Math.PI*2);context.fillStyle=`rgba(224,200,255,${star.a})`;context.fill();});if(!reduced)requestAnimationFrame(draw);} addEventListener('resize',resize);resize();draw();
const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring'); let mouseX=-50,mouseY=-50,ringX=-50,ringY=-50; addEventListener('mousemove',event=>{mouseX=event.clientX;mouseY=event.clientY;dot.style.left=`${mouseX}px`;dot.style.top=`${mouseY}px`;}); function cursorLoop(){ringX+=(mouseX-ringX)*.13;ringY+=(mouseY-ringY)*.13;ring.style.left=`${ringX}px`;ring.style.top=`${ringY}px`;requestAnimationFrame(cursorLoop)} cursorLoop(); document.querySelectorAll('a,button,.project-card,.tags span').forEach(element=>{element.addEventListener('mouseenter',()=>ring.classList.add('hover'));element.addEventListener('mouseleave',()=>ring.classList.remove('hover'));});
const form=document.querySelector('#contact-form'),toast=document.querySelector('#toast'); form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;button.innerHTML='Sending…';const data=Object.fromEntries(new FormData(form));if(API_BASE){try{const response=await fetch(API_BASE+'/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(response.ok){showToast('Message sent. I\u2019ll be in touch soon.');form.reset();button.disabled=false;button.innerHTML='Send a message <span>\u2197</span>';return;}}catch(error){}}const subject=encodeURIComponent('Portfolio enquiry from '+data.name);const body=encodeURIComponent(data.message+'\n\nReply to: '+data.email);window.location.href='mailto:prusty.sampurna@gmail.com?subject='+subject+'&body='+body;showToast('Opening your email app \u2014 message pre-filled \u2726');button.disabled=false;button.innerHTML='Send a message <span>\u2197</span>';}); function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4500);}

if(API_BASE){fetch(API_BASE+'/api/visit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:location.pathname,referrer:document.referrer})}).catch(()=>{})}
